---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family | lower }}.yml"
    - "../vars/default.yml"
  when: openjdk_package_name is not defined

- name: "Check if Java is installed"
  shell: command -v java
  register: check_java
  ignore_errors: True
  changed_when: False
  check_mode: False

- name: "Install OpenJDK"
  package:
    name: "{{ openjdk_package_name }}"
    state: present
  when: check_java.rc != 0
