---
- name: "Render and write out mosquitto broker config"
  template:
    src: mosquitto.conf.j2
    dest: "{{ mosquitto.conf_file }}"

- name: "Upload the Mosquitto MQTT Broker Config"
  shell: az storage file upload --share-name {{ mqtt_broker_share_name }} --account-name {{ storage_account_name }} --account-key {{ storage_account_key }} --source {{ mosquitto.conf_file }} --path config/mosquitto.conf

- name: "Render and write out MQTT connector config"
  template:
    src: mqtt-connector.conf.j2
    dest: "{{ mosquitto.connector_conf_file }}"

- name: "Upload the connector config"
  shell: az storage file upload --share-name {{ mqtt_config_share_name }} --account-name {{ storage_account_name }} --account-key {{ storage_account_key }} --source {{ mosquitto.connector_conf_file }}

- name: "Render and write out consul client config"
  template:
    src: config.json.j2
    dest: "{{ consul.conf_file }}"

- name: "Upload the Consul Config"
  shell: az storage file upload --share-name {{ consul_config_share_name }} --account-name {{ storage_account_name }} --account-key {{ storage_account_key }} --source {{ consul.conf_file }}

- name: "Remove generated files"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ mosquitto.conf_file }}"
    - "{{ mosquitto.connector_conf_file }}"
