---
- name: "Install mosquitto"
  package:
    name: mosquitto
    state: present

- name: "Set the list of MQTT authorized users"
  set_fact: usernames={{ mqtt_users.split(',') }}

- name: "Check if password file exists"
  stat:
    path: "{{ mosquitto.passwd_file }}"
  register: passwd

- name: "Create the password file if not already there"
  file:
    path: "{{ mosquitto.passwd_file }}"
    mode: 0640
    state: touch
  when: not passwd.stat.exists

- name: "Clean up the current password file"
  command:
    mosquitto_passwd -D "{{ mosquitto.passwd_file }}" "{{ item }}"
  when:
    - item.state | default("present") == "absent"
  with_items: "{{ usernames }}"
  no_log: true

- name: "Create new passwords"
  set_fact:
    words: "{{ words|default([]) + [lookup('password', '/dev/null length=8 chars=ascii_letters')] }}"
  with_items: "{{ usernames }}"

- name: "Regen the mosquitto passwords"
  command:
    mosquitto_passwd -b "{{ mosquitto.passwd_file }}" "{{ item.0 }}" "{{ item.1 }}"
  with_together:
    - "{{ usernames }}"
    - "{{ words }}"
  no_log: true

- name: "Save usernames to fact file"
  lineinfile:
    path: "{{ mosquitto.fact_file }}"
    line: "{{ item.0 }} {{ item.1 }}"
    create: yes
  with_together:
    - "{{ usernames }}"
    - "{{ words }}"
  no_log: true

- name: "Upload the Mosquitto paswd file"
  shell: az storage file upload --share-name {{ mqtt_broker_share_name }} --account-name {{ storage_account_name }} --account-key {{ storage_account_key }} --source {{ mosquitto.passwd_file }} --path config/pwfile.txt

- name: "Upload the Mosquitto fact file"
  shell: az storage file upload --share-name {{ mqtt_broker_share_name }} --account-name {{ storage_account_name }} --account-key {{ storage_account_key }} --source {{ mosquitto.fact_file }} --path config/facts.txt

- name: "Render and write out mosquitto broker config"
  template:
    src: mosquitto.conf.j2
    dest: "{{ mosquitto.conf_file }}"

- name: "Upload the Mosquitto MQTT Broker Config"
  shell: az storage file upload --share-name {{ mqtt_broker_share_name }} --account-name {{ storage_account_name }} --account-key {{ storage_account_key }} --source {{ mosquitto.conf_file }} --path config/mosquitto.conf

- name: "Remove generated files"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ mosquitto.fact_file }}"
    - "{{ mosquitto.passwd_file }}"
    - "{{ mosquitto.conf_file }}"
