- name: "Install snap package manager"
  apt:
    name: snap

- name: "Install Intellij community"
  snap:
    name: intellij-idea-community
    classic: yes

- name: "Install pycharm"
  snap:
    name: pycharm-community
    classic: yes

- name: "Install Visual Studio Code"
  snap:
    name: code
    classic: yes

- name: "Install kafka-python"
  pip:
    name: kafka-python
    executable: pip3

- name: "Check if ssh keys exist"
  stat:
    path: /home/vagrant/.ssh/id_rsa
  register: ssh_key

- name: "Create a default ssh key pair"
  shell: ssh-keygen -q -t rsa -N '' -f /home/vagrant/.ssh/id_rsa
  when: not ssh_key.stat.exists

- name: "Update ssh private key ownership and group"
  file:
    path: /home/vagrant/.ssh/id_rsa
    owner: vagrant
    group: vagrant

- name: "Update ssh public key ownership and group"
  file:
    path: /home/vagrant/.ssh/id_rsa.pub
    owner: vagrant
    group: vagrant
