---
- hosts: localhost
  gather_facts: yes
  check_mode: no
  become: True
  tasks:
    - name: "Add public ip addresses to dynamic inventory"
      add_host:
        name: "{{ fqdn }}"

- name: "Configure certbot node"
  hosts: "{{ fqdn }}"
  remote_user: certbot_admin
  become: true
  vars:
    certbot_admin_email: dtufekcic@ctic-inc.com
    certbot_create_if_missing: true
    certbot_auto_renew_user: certbot_admin
    certbot_auto_renew_minute: "35"
    certbot_auto_renew_hour: "9"
    certbot_certs:
      - domains:
          - "{{ fqdn }}"
    nginx_vhosts:
      - listen: "443 ssl http2"
        server_name: "{{ fqdn }}"
        root: "/usr/share/nginx/html"
        index: "index.html index.htm"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "certbot.conf"
        extra_parameters: |
          ssl_certificate     /etc/letsencrypt/live/{{ fqdn }}/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/{{ fqdn }}/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;
  pre_tasks:
    - name: "Update apt cache"
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: "Install dependencies (RedHat)"
      yum:
        name: ["cronie", "epel-release"]
        state: present
      when: ansible_os_family == 'RedHat'

    - name: "Install cron (Debian)"
      apt: name=cron state=present
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.certbot
    - role: geerlingguy.nginx
