---
- name: "Add sbt debian repo to apt"
  shell: echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list

- name: "Add sbt key to apt"
  shell: curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add

- name: "Update apt"
  apt:
    update_cache: yes

- name: "Install sbt"
  apt: name=sbt

- name: "Clone connector repo"
  git:
    repo: 'https://github.com/Azure/toketi-kafka-connect-iothub.git'
    dest: /tmp/iot-hub-connector

- name: "Build connector jar"
  shell: cd /tmp/iot-hub-connector && sbt assembly

- name: "Copy connector jar(s)"
  shell: find /tmp/iot-hub-connector/target/ -name "*.jar" | xargs -i cp -p {} /usr/local/kafka/libs/

- name: "Copy connector config file"
  copy:
    src: /tmp/connect-iothub-source.properties
    dest: /etc/kafka/connect-iothub-source.properties
    owner: root
    group: root
    mode: 0644
  become: yes


