---
- name: "Start the connector"
  shell: nohup /usr/local/kafka/bin/connect-standalone.sh /etc/kafka/connect-standalone.properties /etc/kafka/connect-iothub-source.properties &
  become: yes

- name: "Wait for 10s after starting connector"
  wait_for: timeout=10

- name: "Get the connector process ID"
  shell: ps -ef | grep connect-iothub-source.properties | awk '{print $2}'
  register: connector_pid

- debug:
    var: connector_pid

- name: "Check pid is active"
  fail: msg="Connector didn't start correctly"
  when: connector_pid.stdout_lines[0] is not defined