== Data Science Infrastructure Deployment

Use this project to deploy an instance of a data science pipeline to Azure using Terraform and Ansible.

Currently, the main Terraform datasci.tf script deploys the following resources to Azure.

- A Resource Group (optional)
- A Virtual Network
- A Subnet for the CentOS VM worker nodes
- A Network Security Group for worker nodes
- A storage accounts for boot diagnostics
- An Event Hubs Namespace, and an Event Hub instance per specified MQTT topic
- An Azure data lake storage container
- A CentOS VM with PostgreSQL v10 for the Apache Spark job state
- A set of CentOS VM worker nodes with Apache Spark, HDFS, YARN, Jupyter Notebook, and Consul
- A set of Azure Databases for PostgreSQL server use with Grafana server

=== Step-by-step Guide
The data-science project is meant to be deployed from a DevOps Docker container which includes all the needed tools pre-installed and configured. To get started,

. `Install Docker` by following directions http://docs.docker.com/engine/install[here]
. In a terminal, run `docker run -dit --name datasci chesapeaketechnology/devops:latest /bin/bash` to download the container image
. Log into the newly downloaded container by running `docker exec -u 0 -it datasci /bin/bash`
. Set the needed environment variables as shown in the example below.

[source,bash]
----
## Set Pipeline Environment Variables
export WORKING_DIR="/opt/repos"
export TF_VAR_location="eastus" # For Azure US Government: export TF_VAR_location="usgovvirginia"
export TF_VAR_environment="dev"
export TF_VAR_cluster_name="datasci"
export TF_VAR_resource_group_name="rg-${TF_VAR_cluster_name}-${TF_VAR_environment}"
export TF_VAR_tfstate_resource_group_name="rg-${TF_VAR_cluster_name}-tfstate-${TF_VAR_environment}"
export TF_VAR_state_container="remote-tfstates"
export TF_VAR_default_tags=$(printf '{"Department"="Engineering","PoC"="Me","Environment"="%s","IaC_Managed"="Yes"}' $(echo ${TF_VAR_environment^^}))
export TF_VAR_alert_topics='["alert_message"]'
export TF_VAR_mqtt_topics='["comma","separated","list"]'
export TF_VAR_jobs='["analysis_job1","analysis_job2"]'

# Azure Account Credentials
export ARM_ENVIRONMENT="public"
export ARM_CLIENT_ID="azure-serviceprincipal-client-id"
export ARM_CLIENT_SECRET="azure-serviceprincipal-secret"
export ARM_SUBSCRIPTION_ID="azure-subscription-id"
export ARM_TENANT_ID="azure-tenant-id"

# Remote State Azure Account Credentials (if in different resource group than assets...and it should be! If not, just source the ARM ENVs)
export TF_VAR_remotestate_client_id="azure-serviceprincipal-client-id"
export TF_VAR_remotestate_client_secret="azure-serviceprincipal-secret"
export TF_VAR_remotestate_subscription_id="${ARM_SUBSCRIPTION_ID}"
export TF_VAR_remotestate_tenant_id="${ARM_TENANT_ID}"
export TF_VAR_remotestate_storage_account_name="${TF_VAR_environment}tfstate${TF_VAR_cluster_name}001"
export TF_VAR_sp_password="${ARM_CLIENT_SECRET}"
----

[start=5]
. Clone the data-science repo by running:
[source,bash]
----
mkdir -p ${WORKING_DIR}
cd ${WORKING_DIR}
git clone https://github.com/chesapeaketechnology/data-science.git
cd data-science/
git checkout master
echo $(pwd)
echo "We should be ready to fire away."
----

[start=6]
. *First Time Only*: This step should only be done if this is the first time you're deploying the data-science repo to your environment or if you're re-deploying to an existing environment following a complete destruction of the environment (i.e. the Terraform remote state storage account does not have any state information on the environment you're about to deploy).

[source,bash]
----
cd ${WORKING_DIR}/data-science/terraform/remote-state-bootstrap
unset ARM_CLIENT_ID
unset ARM_CLIENT_SECRET
export ARM_CLIENT_ID="${TF_VAR_remotestate_client_id}"
export ARM_CLIENT_SECRET="${TF_VAR_remotestate_client_secret}"
terraform init
terraform plan
terraform import azurerm_resource_group.resource_group /subscriptions/${ARM_SUBSCRIPTION_ID}/resourceGroups/${TF_VAR_tfstate_resource_group_name}
terraform apply -auto-approve
# OCD optional cleanup (is ignored by Git via .gitignore)
rm -fr ./.terraform *.tfstate*
unset ARM_CLIENT_ID
unset ARM_CLIENT_SECRET
echo "SET THE PROPER VARS AGAIN FOR ARM_CLIENT_ID & ARM_CLIENT_SECRET"
----

[start=7]
. Log into Azure CLI

[source,bash]
----
az account clear
az login --service-principal --username ${ARM_CLIENT_ID} --tenant ${ARM_TENANT_ID} --password ${ARM_CLIENT_SECRET}
----

[start=8]
. Deploy the *infrastructure* resources of the project

NOTE: There is a capability to toggle the management (import/create) of resource groups. To change this default behavior, set "TF_VAR_manage_resource_group=True".

[source,bash]
----
cd ${WORKING_DIR}/data-science/terraform/providers/infrastructure
terraform init \
-backend-config="key=${TF_VAR_environment}/$(basename $(pwd)).tfstate" \
-backend-config="resource_group_name=${TF_VAR_tfstate_resource_group_name}" \
-backend-config="storage_account_name=${TF_VAR_remotestate_storage_account_name}" \
-backend-config="container_name=${TF_VAR_state_container}" \
-backend-config="client_id=${TF_VAR_remotestate_client_id}" \
-backend-config="client_secret=${TF_VAR_remotestate_client_secret}" \
-backend-config="subscription_id=${TF_VAR_remotestate_subscription_id}" \
-backend-config="tenant_id=${TF_VAR_remotestate_tenant_id}"
terraform plan
terraform apply
----

[start=9]
. Deploy the *application* resources of the project

[source,bash]
----
cd ${WORKING_DIR}/data-science/terraform/providers/application_stack
terraform init \
-backend-config="key=${TF_VAR_environment}/$(basename $(pwd)).tfstate" \
-backend-config="resource_group_name=${TF_VAR_tfstate_resource_group_name}" \
-backend-config="storage_account_name=${TF_VAR_remotestate_storage_account_name}" \
-backend-config="container_name=${TF_VAR_state_container}" \
-backend-config="client_id=${TF_VAR_remotestate_client_id}" \
-backend-config="client_secret=${TF_VAR_remotestate_client_secret}" \
-backend-config="subscription_id=${TF_VAR_remotestate_subscription_id}" \
-backend-config="tenant_id=${TF_VAR_remotestate_tenant_id}"
terraform plan
terraform apply
----

=== Troubleshooting
* After running a full `terraform destroy` and Azure still shows 2 resources (Network security group and Virtual Network), execute the following:
** This assumes you are logged into the container per the Deployment Process

[source,bash]
----
az network profile delete --id $(az network profile list | jq -r '.[].id') -y
az network vnet delete --resource-group $(az network vnet list | jq -r '.[].resourceGroup') --name $(az network vnet list | jq -r '.[].name')
az network nsg delete --resource-group $(az network nsg list | jq -r '.[].resourceGroup') --name $(az network nsg list | jq -r '.[].name')
----


* If you get an error about _"The subscription is not registered to use namespace Microsoft.Network"_, then use the steps on the following page to register the *Microsoft.Network* resource provider.
** https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/error-register-resource-provider
** Something like:
*** `az provider register --namespace Microsoft.Network`