---
- name: "Install python-consul module"
  pip:
    name: python-consul
 
- name: "Register all deployed eventhubs"
  include_tasks: azure-namespace-facts.yml
  loop: "{{ namespaces.split(',') }}"
  loop_control:
    loop_var: namespace_item