---
- name: Copy slaves into place
  template:
    src: slaves
    dest: /usr/local/hadoop/etc/hadoop/slaves
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group}}"

- name: Prepare known_hosts entries
  shell: ssh-keyscan -t rsa "{{ item }}"
  with_items: "{{ groups['nodes'] }}"
  register: keyscans

- name: Prepare known_hosts
  lineinfile:
    dest: "/home/{{ hadoop_user }}/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ item.stdout }}"
    regexp: "^{{ item.item }}"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
  with_items: "{{ keyscans.results }}"

- name: Prepare known_hosts entries
  shell: ssh-keyscan -t rsa 0.0.0.0
  register: keyscan_0_0_0_0

- name: Add 0.0.0.0 to known_hosts for secondary namenode
  lineinfile:
    dest: "/home/{{ hadoop_user }}/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ keyscan_0_0_0_0.stdout }}"
    regexp: "^0.0.0.0"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
