---
- name: "Configure machine with development and datasci packages"
  hosts: all
  gather_facts: yes
  check_mode: no
  become: True
  roles:
      - role: "configure-datasci/roles/common"
      - role: "configure-datasci/roles/azure-cli"
      - role: "dev-env"
      - role: "configure-datasci/roles/zookeeper"
      - {
        role: "configure-datasci/roles/kafka",
        kafka_hosts: ['localhost'],
        kafka_zookeeper_hosts: "{{ zookeeper_hosts | list }}",
        kafka_version: 2.4.0,     # Kafka version override.
        kafka_scala_serverion: 2.11 # Scala version override.
      }
      - {
        role: "configure-datasci/roles/spark",
        spark_master_ip: "{{ groups['nodes'][0] }}"
      }
      - role: "configure-datasci/roles/spark-cluster-admin"
      - role: "configure-datasci/roles/notebook"
