- name: "Install Jupyter notebook using pip"
  pip:
    name: notebook
    executable: pip3

- name: "Install pyspark python module"
  pip:
    name: pyspark
    executable: pip3

- name: "Install python3 kernel"
  shell: python3 -m pip install ipykernel

- name: "Make python3 kernel available"
  shell: python3 -m ipykernel install --user

- name: "Start the notebook server"
  shell: nohup jupyter notebook --no-browser --allow-root &
  register: out

- debug: var=out.stderr_lines
