- name: "Install Jupyter notebook using pip"
  pip:
    name: notebook
    executable: pip3

- name: "Install pyspark python module"
  pip:
    name: pyspark
    executable: pip3

- name: "Install python3 kernel"
  shell: python3 -m pip install ipykernel

- name: "Make python3 kernel available"
  shell: python3 -m ipykernel install --user

- include: config.yml

- name: "Start the notebook server"
  shell: "nohup {{ jupyter_home }}/jupyter notebook --no-browser &"
  register: out
  become_user: "{{ jupyter_user }}"

- debug: var=out.stderr_lines
