---
- hosts: localhost
  gather_facts: yes
  check_mode: no
  tasks:
    - name: "Render and write out mqtt connector config"
      template:
        src: mqtt-connector.conf.j2
        dest: /tmp/mqtt-connector.conf

    - name: "Upload the connector config"
      shell: az storage file upload --share-name {{ mqtt_config_share_name }} --account-name {{ storage_account_name }} --account-key {{ storage_account_key }} --source /tmp/mqtt-connector.conf
