---
- name: "Get resource group"
  shell: grep -A 1 master inventory.ini | awk 'NR>1 { print $1 }' | cut -d'.' -f1 | sed 's/[0-9+]$//' | sed 's/$/-group/' | sed 's/-/_/g'
  register: resource_group

- debug:
    var: resource_group.stdout_lines[0]

- name: "Get the count of iot hubs"
  shell: az iot hub list --resource-group {{ resource_group.stdout_lines[0] }} | grep path | wc -l
  register: iothub_count

- debug:
    var: iothub_count.stdout_lines[0]

- name: "Check the count"
  fail: msg="Found {{ iothub_count.stdout_lines[0] }} iot hubs in {{ resource_group.stdout_lines[0] }}. Can't determine which one to use."
  when: iothub_count.stdout_lines[0] != '1'

- name: "Get IoT hub name"
  shell: az iot hub list | grep path | awk '{print $2}' | sed 's/[",]//g'
  register: iothub_name

- debug:
    var: iothub_name.stdout_lines[0]

- name: "Set topic_name fact"
  set_fact: iothub_topic_name="IoTHub"

- name: "Get iot hub connection endpoint"
  shell: az iot hub show --name {{ iothub_name.stdout_lines[0] }} | grep -m 1 endpoint | awk '{print $2}' | sed 's/[",]//g'
  register: iothub_endpoint

- debug:
    var: iothub_endpoint.stdout_lines[0]

- name: "Get shared access key for service policy"
  shell: az iot hub policy show --name service --hub-name {{ iothub_name.stdout_lines[0] }} | grep primaryKey | awk '{print $2}' | sed 's/[",]//g'
  register: iothub_key

- debug:
    var: iothub_key.stdout_lines[0]

- name: "Get partition count"
  shell:  az iot hub show --name {{ iothub_name.stdout_lines[0] }} | grep partitionCount | awk '{print $2}' | sed 's/,//g'
  register: iothub_partition_count

- debug:
    var: iothub_partition_count.stdout_lines[0]

- name: "Render and write out the connector conf file"
  template: src=usr/local/kafka/config/connect-iothub-source.properties.j2 dest="/tmp"