---
- hosts: localhost
  gather_facts: yes
  check_mode: no
  become: false
  tasks:
    - name: "Parse host groups from inventory list"
      shell: echo "{{ inventory }}" | tr , '\n' | awk -F ":" '{print $1}'
      register: group_list
      changed_when: false

    - debug:
        var: group_list

    - name: "Parse host public ip addresses from inventory list"
      shell: echo "{{ inventory }}" | tr , '\n' | awk -F ":" '{print $2}'
      register: hosts
      changed_when: false

    - debug:
        var: hosts

    - name: "Parse host FQDN from inventory"
      shell: echo "{{ inventory }}" | tr , '\n' | awk -F ":" '{print $3}'
      register: fqdn_list
      changed_when: false

    - debug:
        var: fqdn_list

    - name: "Parse host private ip addresses from inventory"
      shell: echo "{{ inventory }}" | tr , '\n' | awk -F ":" '{print $4}'
      register: pip_list
      changed_when: false

    - debug:
        var: pip_list

    - name: "Add public ip addresses to dynamic inventory"
      add_host:
        name: "{{ item }}"
        groups: "{{ group_list.stdout_lines[0] }}"
        public_ips: "{{ hosts.stdout_lines }}"
        private_ips: "{{ pip_list.stdout_lines }}"
        fqdns: "{{ fqdn_list.stdout_lines }}"
      with_items: "{{ hosts.stdout_lines }}"
      changed_when: false

- hosts: all
  gather_facts: yes
  check_mode: no
  become: True
  tasks:
    - name: "Install python 2.7"
      raw: >
        test -e /usr/bin/python ||
        (
          (sudo apt install python)
        )
      args:
        creates: /usr/bin/python

- name: "Configure worker VM nodes"
  hosts: all
  remote_user: datasci_admin
  become: true
  pre_tasks:
    - include_vars: azurevars.yml
    - include_vars: securevars.yml
  roles:
    - {
      role: "consul",
      is_leader: "{{ inventory_hostname == public_ips[0] }}"
    }
    - role: geerlingguy.java
      java_packages:
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel
    - role: cloudalchemy.node-exporter
    - role: "common"
    - role: "hadoop"
    - {
      role: "spark",
      spark_master_ip: "{{ private_ips[0] }}"
    }
    - role: "spark-cluster-admin"
    - role: "notebook"

- name: "Store all Azure deployment facts to Consul from one node"
  hosts: "{{ groups['nodes'][0] }}"
  become: true
  tasks:
    - name: "Azure deployment role"
      include_tasks: "roles/azure-deployment-facts/tasks/main.yml"

- name: "Start hadoop on one of the nodes"
  hosts: "{{ groups['nodes'][0] }}"
  remote_user: hadoop
  tasks:      
    - name: "Format namenode"
      shell: hadoop namenode -format -force -nonInteractive

    - name: "Start hdfs"
      shell: start-dfs.sh

    - name: "Start Yarn"
      shell: start-yarn.sh