---
- hosts: localhost
  gather_facts: yes
  check_mode: no
  tasks:
    - name: "Parse host ip addresses from inventory list"
      shell: echo "{{ inventory }}" | sed 's/,/\n/g' | sed 's/\(.*\)://g'
      register: hosts

    - debug:
        var: hosts

    - name: "Parse host groups from inventory list"
      shell: echo "{{ inventory }}" | sed 's/,/\n/g' | sed 's/:\(.*\)//g'
      register: group_list

    - debug:
        var: group_list

    - name: "Add public ip addresses to an dynamic inventory"
      add_host:
        name: "{{ item }} "
        groups: "{{ group_list.stdout_lines[0] }}"
      with_items: "{{ hosts.stdout_lines }}"
  roles:
      - role: "azure-cli"
      - role: "iothub-query"

- hosts: all
  gather_facts: yes
  check_mode: no
  become: True
  tasks:
    - name: "Install python 2.7"
      raw: >
        test -e /usr/bin/python ||
        (
          (sudo apt install python)
        )
      args:
        creates: /usr/bin/python

- name: "Configure VM nodes"
  hosts: all
  remote_user: datasci_admin
  become: true
  roles:
    - role: "common"
    - role: "zookeeper"
    - {
      role: "kafka",
      kafka_hosts: "{{ groups.nodes | list }}",
      kafka_zookeeper_hosts: "{{ zookeeper_hosts | list }}",
      kafka_version: 2.4.0,     # Kafka version override.
      kafka_scala_serverion: 2.11 # Scala version override.
    }
    - role: "azure-connector"
    - role: "spark"
    - role: "spark-cluster-admin"
    - role: "notebook"
