---
- name: "Install unzip"
  apt:
    name: unzip

- name: "Download Terraform binary"
  get_url:
    url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: /home/vagrant/

- name: "Unzip Terraform"
  shell: unzip /home/vagrant/terraform_{{ terraform_version }}_linux_amd64.zip

- name: "Install Terraform"
  shell: mv /home/vagrant/terraform /usr/local/bin

- name: "Remove the zip"
  shell: rm /home/vagrant/terraform_{{ terraform_version }}_linux_amd64.zip
