---
# Azure Environment Variables
location: "eastus"

# Data Science Global Variables
environment: "dev"
cluster_name: "datasci"
department: "LiveStream"
poc: "Monkey"
admin_username: "datasciadmin"

# Node Information
node_count: 3
ansible_pwfile: "~/.vaultpw"
# MQTT Data
mqtt_topics: ["test1", "test2"]
mqtt_users: ["user1", "user2"]
alert_topics: ["alert_message"]
